### ISSUE TITLE
Music not uploading

### ISSUE THREAD

**Issue by adriaanh** [jaymoulin/youtube-music-uploader#1]
Version Number: 1.0.0

```
1.0.0
```

**Description**
The files are not getting uploaded to Youtube. 

**Steps to reproduce the issue:**
1. Create docker container including the dedup API  (https://github.com/jaymoulin/google-musicmanager-dedup-api)
2. Follow instructions for receiving cookie information.
3. Watch the log grow

**Describe the results you received:**
Log of one song, however this is the same for all songs. 

```
youtubemusicuploader | 2020-10-22 20:07:22,130 - youtube_music_uploader.uploader_daemon - INFO - Should upload /media/library/Country/John Denver - The Essential John Denver 2007(2cd's)/CD1/14 - Thank God I'm A Country Boy.mp3?
youtubemusicdedup | 172.18.0.3 - - [22/Oct/2020 20:07:22] "GET / HTTP/1.1" 404 -
youtubemusicuploader | 2020-10-22 20:07:22,139 - youtube_music_uploader.uploader_daemon - INFO - Deduplicate API: file exists? no
youtubemusicuploader | 2020-10-22 20:07:22,140 - youtube_music_uploader.uploader_daemon - INFO - Uploading /media/library/Country/John Denver - The Essential John Denver 2007(2cd's)/CD1/14 - Thank God I'm A Country Boy.mp3
youtubemusicuploader | 2020-10-22 20:07:22,867 - youtube_music_uploader.uploader_daemon - INFO - Not uploaded /media/library/Country/John Denver - The Essential John Denver 2007(2cd's)/CD1/14 - Thank God I'm A Country Boy.mp3
```

**Describe the results you expected:**
I expected the music to get uploaded.

**Additional information you deem important (e.g. issue happens only occasionally):**
* I have verified that the oauth key has been created
* I tried on both a linux and windows docker environment
* And thank you for creating this API. With Google Play Music EOL and the music manager not working anymore, this would really be useful!

**Comment by kahn10** [comment]
I think I'm having the same problem, though I can't figure out where the logs are. There's nothing showing up in console. I'm currently running it in docker, and I don't see any traffic or disk reads happening in docker stats.

**Comment by jaymoulin** [comment]
I confirm today that the actual version `1.0.0` is working following the given guidlines for both MP3 and WAV files

```
youtubemusic_1  | 2020-11-24 12:41:41,860 - youtube_music_uploader.uploader_daemon - INFO - Should upload /media/library/MUR_SINGLE_MIX_CASTE.wav?                                                                 
youtubemusic_1  | 2020-11-24 12:41:41,861 - youtube_music_uploader.uploader_daemon - INFO - Uploading /media/library/MUR_SINGLE_MIX_CASTE.wav                                                                      
youtubemusic_1  | 2020-11-24 12:41:41,906 - youtube_music_uploader.uploader_daemon - INFO - Should upload /media/library/Unearth/III: In The Eyes Of Fire/9 - Imposter's Kingdom.mp3?                              
youtubemusic_1  | 2020-11-24 12:41:41,907 - youtube_music_uploader.uploader_daemon - INFO - Uploading /media/library/Unearth/III: In The Eyes Of Fire/9 - Imposter's Kingdom.mp3                                   
youtubemusic_1  | 2020-11-24 12:41:46,725 - youtube_music_uploader.uploader_daemon - INFO - Should upload /media/library/Unearth/III: In The Eyes Of Fire/3 - March of the Mutes.mp3? 
```

Please make sure that your `oauth.key` file contains correct headers (starting from `Accept` included) + cookie in a json format, and you actually are connected to your Youtube Music interface so the cookie is still active
