### ISSUE TITLE
Meaning of "Response 409"

### ISSUE THREAD

**Issue by SirYaro** [jaymoulin/youtube-music-uploader#5]
Version Number: 1.3.0

Hi.
I'd like to ask what "Response 409" means. Like in:

```
[...]22:10:36,160 - youtube_[...]_daemon - INFO - Should upload ./A/AAA/BBB/04 Boogie.mp3? 
[...]22:10:36,160 - youtube[...]aemon - INFO - Uploading ./A/AAA/BBB/04 Boogie.mp3
[...]22:10:40,999 - youtub[...]aemon - INFO - Not uploaded ./A/AAA/BBB/04 Boogie.mp3: <Response [409]>
[...]22:10:41,000 - youtube[...]daemon - INFO - Should upload ./A/AAA/BBB/08 Bomb.mp3? 
[...]22:10:41,000 - youtu[...]aemon - INFO - Uploading ./A/AAA/BBB/08 Bomb.mp3
[...]22:10:45,369 - youtu[...]daemon - INFO - Not uploaded ./A/AAA/BBB/08 Bomb.mp3: <Response [409]>
```

Is that mean file already exists on YTM side? I checked like 20 of such responses, and they all were there, so I'm fairly certain at this point, but I'd like to confirm that with you...

Thank you

**Comment by jaymoulin** [comment]
Hello and thank you for your interest in Youtube Music Uploader. As you stated, 409 stand for 'Conflict' which means your music already exist on your profile. You may be interest in https://github.com/jaymoulin/google-musicmanager-dedup-api and its use (https://github.com/jaymoulin/youtube-music-uploader#deduplication-api) to avoid this.

If you find these products useful, please consider donate [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin)[![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/jaymoulin)
