### ISSUE TITLE
youtube-music-auth is broken because ytmusicapi has changed

### ISSUE THREAD

**Issue by brian-doherty** [jaymoulin/youtube-music-uploader#6]
Version Number: 1.3.0

**If you're using docker, Output of `docker inspect jaymoulin/youtube-music-uploader --format='{{index .Config.Labels.version}}'`:**

```
(paste your output here)
```

**Description**

When running youtube-music-auth the following error message appears:

Traceback (most recent call last):
  File "/home/brian/.local/bin/youtube-music-auth", line 8, in <module>
    sys.exit(main())
  File "/home/brian/.local/lib/python3.10/site-packages/youtube_music_uploader/auth.py", line 17, in main
    auth(sys.argv[1] if len(sys.argv) > 1 else os.environ['HOME'] + '/oauth')
  File "/home/brian/.local/lib/python3.10/site-packages/youtube_music_uploader/auth.py", line 12, in auth
    if YTMusic.setup(auth_file):
AttributeError: type object 'YTMusic' has no attribute 'setup'

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by jaymoulin** [comment]
Thank you for your PR. Rebased and merged in latest 1.3.1 release.
